# post_processing_panel.py

import sys
import random
import math

from PyQt5.QtWidgets import (QWidget, QPushButton, QGraphicsScene, QGraphicsView,
                             QGraphicsRectItem, QGraphicsEllipseItem, QSpinBox, QLabel, QVBoxLayout,
                             QGraphicsLineItem, QDoubleSpinBox, QComboBox)
from PyQt5.QtCore import Qt, QLineF, QPointF
from PyQt5.QtGui import QPen, QColor, QBrush # Ensure QBrush is imported

# Import necessary classes
from core.map import Map
from core.node import Node
from core.logger import logger
from typing import TYPE_CHECKING, Optional, List, Tuple

# Import PostProcessingManager and base class
from post_processing.post_processing_manager import PostProcessingManager
from core.post_processing_algorithm import PostProcessingAlgorithm

if TYPE_CHECKING:
    from core.algorithm import Algorithm

SCALE = 6

class PostProcessingPanel(QWidget):
    """
    A QWidget panel for visualizing and applying post-processing algorithms
    to paths generated by a planning algorithm.
    """
    def __init__(self, panel_id: str):
        super().__init__()
        self.panel_id = panel_id
        logger.info(f"Initializing PostProcessingPanel '{self.panel_id}'")

        try: self.pp_manager = PostProcessingManager()
        except Exception as e: logger.error(f"Panel {self.panel_id}: Failed to initialize PostProcessingManager: {e}", exc_info=True); self.pp_manager = None

        self.current_map: Optional[Map] = None
        self.original_path: Optional[list] = None
        self.processed_path: Optional[List[QPointF]] = None
        self.algorithm_instance: Optional['Algorithm'] = None

        self.scene = QGraphicsScene()
        self.view = QGraphicsView(self.scene)
        self.view.setFixedSize(int(100 * SCALE) + 16, int(100 * SCALE) + 16)

        # --- Controls ---
        self.pp_algo_selector_label = QLabel("Post-Processing Algorithm:")
        self.pp_algo_selector = QComboBox()
        if self.pp_manager: self.pp_algo_selector.addItems(self.pp_manager.get_algorithm_names())
        else: self.pp_algo_selector.addItem("Manager Failed"); self.pp_algo_selector.setEnabled(False)

        self.process_button = QPushButton('Run Post-Processing')
        if not self.pp_manager: self.process_button.setEnabled(False)

        self.parameter_label = QLabel('Iterations / Samples:')
        self.parameter_input = QSpinBox()
        self.parameter_input.setRange(1, 50000)
        self.parameter_input.setValue(100)

        # --- Button Connections ---
        self.process_button.clicked.connect(self.run_post_processing)

        # --- Layout ---
        layout = QVBoxLayout()
        layout.addWidget(QLabel(f"--- Panel {self.panel_id} ---"))
        layout.addWidget(self.view)
        layout.addWidget(self.pp_algo_selector_label)
        layout.addWidget(self.pp_algo_selector)
        layout.addWidget(self.parameter_label)
        layout.addWidget(self.parameter_input)
        layout.addWidget(self.process_button)
        self.setLayout(layout)

        self.clear_display()

    # --- Coordinate Conversion ---
    def map_to_display(self, x: float, y: float) -> Tuple[float, float]:
        return x * SCALE, y * SCALE

    # --- Data Handling ---
    def update_data(self, map_instance: Optional[Map], shortest_path: Optional[list], algorithm_instance: Optional['Algorithm']):
        # (Logic remains the same)
        path_len = len(shortest_path) if shortest_path else 0
        algo_name = algorithm_instance.__class__.__name__ if algorithm_instance else "None"
        map_status = 'Set' if map_instance else 'None'
        logger.info(f"Panel {self.panel_id}: Received data. Map: {map_status}, Path points: {path_len}, Algorithm: {algo_name}")
        self.current_map = map_instance; self.original_path = shortest_path
        self.algorithm_instance = algorithm_instance; self.processed_path = None
        if not self.current_map or not self.algorithm_instance or not self.original_path:
            missing = [];
            if not self.current_map: missing.append("Map")
            if not self.algorithm_instance: missing.append("Algorithm Instance")
            if not self.original_path: missing.append("Original Path")
            logger.warning(f"Panel {self.panel_id}: Cannot update display fully, missing prerequisites: {', '.join(missing)}.")
            self.clear_display(); return
        try:
            view_width = int(self.current_map.width * SCALE) + 16
            view_height = int(self.current_map.height * SCALE) + 16
            self.view.setFixedSize(view_width, view_height)
            self.scene.setSceneRect(0, 0, float(self.current_map.width * SCALE), float(self.current_map.height * SCALE))
        except Exception as e: logger.error(f"Panel {self.panel_id}: Error setting view/scene size: {e}")
        self.draw_paths()

    def clear_display(self):
        # (Logic remains the same)
        self.scene.clear(); self.current_map = None; self.original_path = None
        self.processed_path = None; self.algorithm_instance = None
        text = self.scene.addText("Waiting for path data...")
        text.setDefaultTextColor(Qt.gray); self.view.viewport().update()


    # --- Drawing ---
    def draw_paths(self):
        """Draws the map obstacles, original path, and processed path onto the scene."""
        self.scene.clear()

        if not self.current_map: logger.warning(f"Panel {self.panel_id}: Cannot draw, map missing."); self.clear_display(); return

        # 1. Draw Obstacles
        for ox, oy, w, h in self.current_map.get_obstacles(): dx, dy = self.map_to_display(ox, oy); dw, dh = w * SCALE, h * SCALE; obstacle = QGraphicsRectItem(dx, dy, dw, dh); obstacle.setBrush(Qt.lightGray); obstacle.setPen(QPen(Qt.gray)); self.scene.addItem(obstacle)

        # 2. Draw Original Path (Blue Dashed)
        pen_original = QPen(QColor("blue"), 1.5); pen_original.setStyle(Qt.DashLine)
        if self.original_path and len(self.original_path) > 1:
            for i in range(len(self.original_path) - 1):
                p1 = self.original_path[i]; p2 = self.original_path[i+1]
                # --- CORRECTED INDENTATION ---
                if p1 is None or p2 is None: logger.warning(f"Panel {self.panel_id}: Found None in original path at index {i}."); continue
                try:
                    x1, y1 = p1.x, p1.y; x2, y2 = p2.x, p2.y
                    dx1, dy1 = self.map_to_display(x1, y1); dx2, dy2 = self.map_to_display(x2, y2)
                    line = QGraphicsLineItem(QLineF(dx1, dy1, dx2, dy2))
                    line.setPen(pen_original); self.scene.addItem(line)
                except AttributeError: logger.error(f"Panel {self.panel_id}: Original path node lacks .x or .y attribute at index {i}. Point: {p1}", exc_info=True); break
                except Exception as e: logger.error(f"Panel {self.panel_id}: Unexpected error drawing original path segment {i}: {e}", exc_info=True); break
                # --- END CORRECTION ---

        # 3. Draw Processed Path (Red Solid)
        pen_processed = QPen(QColor("red"), 2.5)
        if self.processed_path and len(self.processed_path) > 1:
            for i in range(len(self.processed_path) - 1):
                p1 = self.processed_path[i]; p2 = self.processed_path[i+1]
                # --- CORRECTED INDENTATION ---
                if p1 is None or p2 is None: logger.warning(f"Panel {self.panel_id}: Found None in processed path at index {i}."); continue
                try:
                    line = QGraphicsLineItem(QLineF(p1, p2))
                    line.setPen(pen_processed); self.scene.addItem(line)
                except Exception as e: logger.error(f"Panel {self.panel_id}: Unexpected error drawing processed path segment {i}: {e}", exc_info=True); break
                # --- END CORRECTION ---

        # 4. Draw Start/Goal points for visual reference
        point_size = 2 * SCALE
        if self.original_path:
            # --- CORRECTED INDENTATION ---
            try:
                # Start Point
                start_node = self.original_path[0]
                if start_node:
                    sx, sy = start_node.x, start_node.y
                    dsx, dsy = self.map_to_display(sx, sy)
                    start_ellipse = QGraphicsEllipseItem(dsx - point_size / 2 , dsy - point_size / 2, point_size, point_size)
                    start_ellipse.setBrush(Qt.green)
                    no_pen = QPen(); no_pen.setStyle(Qt.NoPen)
                    start_ellipse.setPen(no_pen)
                    self.scene.addItem(start_ellipse)

                # Goal Point
                goal_node = self.original_path[-1]
                if goal_node:
                    gx, gy = goal_node.x, goal_node.y
                    dgx, dgy = self.map_to_display(gx, gy)
                    goal_ellipse = QGraphicsEllipseItem(dgx - point_size / 2 , dgy - point_size / 2, point_size, point_size)
                    no_brush = QBrush(); no_brush.setStyle(Qt.NoBrush)
                    goal_ellipse.setBrush(no_brush)
                    goal_ellipse.setPen(QPen(Qt.red, 1.5))
                    self.scene.addItem(goal_ellipse)
            except AttributeError: logger.error(f"Panel {self.panel_id}: Start/goal node lacks .x or .y attribute.", exc_info=True)
            except IndexError: logger.error(f"Panel {self.panel_id}: Original path list seems empty.", exc_info=True)
            except Exception as e: logger.error(f"Panel {self.panel_id}: Error drawing start/goal points: {e}", exc_info=True)
            # --- END CORRECTION ---

        self.view.viewport().update()


    # --- Post-Processing Logic ---
    def run_post_processing(self):
        """
        Gets the selected post-processing algorithm, instantiates it,
        and runs its 'process' method on the current original path.
        Updates the display with the result.
        """
        if not self.pp_manager: logger.error(f"Panel {self.panel_id}: PP Manager missing."); return
        if not self.algorithm_instance: logger.warning(f"Panel {self.panel_id}: Planner instance missing."); return
        if not self.original_path or len(self.original_path) < 2: logger.warning(f"Panel {self.panel_id}: Original path missing/short."); return

        selected_algo_name = self.pp_algo_selector.currentText()
        SelectedAlgoClass = self.pp_manager.get_algorithm_class(selected_algo_name)

        if not SelectedAlgoClass: logger.error(f"Panel {self.panel_id}: Could not find class for '{selected_algo_name}'."); return

        logger.info(f"Panel {self.panel_id}: Running post-processing algorithm '{selected_algo_name}'...")

        input_path_nodes = list(self.original_path) # Use copy

        try:
            pp_instance = SelectedAlgoClass()
            process_kwargs = {
                'iterations': self.parameter_input.value(),
                'num_samples': self.parameter_input.value(),
            }

            processed_node_list: List[Node] = pp_instance.process(
                original_path=input_path_nodes,
                algorithm_instance=self.algorithm_instance,
                **process_kwargs
            )

            self.processed_path = []
            if processed_node_list:
                 for node in processed_node_list:
                     if node is None: logger.warning(f"Panel {self.panel_id}: PP algorithm returned None in path list."); continue
                     try: dx, dy = self.map_to_display(node.x, node.y); self.processed_path.append(QPointF(dx, dy))
                     except AttributeError: logger.error(f"Panel {self.panel_id}: Result node lacks .x or .y attribute. Node: {node}", exc_info=True); self.processed_path = None; break
                     except Exception as e: logger.error(f"Panel {self.panel_id}: Error converting result node {node}: {e}", exc_info=True); self.processed_path = None; break
            else: logger.warning(f"Panel {self.panel_id}: PP algorithm '{selected_algo_name}' returned empty/None path."); self.processed_path = None
            self.draw_paths()

        except Exception as e:
             logger.error(f"Panel {self.panel_id}: Error executing PP algorithm '{selected_algo_name}': {e}", exc_info=True)
             self.processed_path = None; self.draw_paths() # Clear processed path on error